# Generated by Django 3.2.7 on 2022-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descriptiona',
            field=models.CharField(db_index=True, default='Anonymous', max_length=10000, verbose_name='Description'),
        ),
    ]
